### PR TITLE
Remove vars/main.yml and move vars to defaults/main.yml

### PR DESCRIPTION
**Pull request by lunarthegrey**
This would be the proper way to do it in an Ansible role, otherwise you have to change vars/main.yml to change the version. If you add it to the vars in your playbook it doesn't override it. Without these changes you can't specify the vars in your playbook and have the version change.

### CODE REVIEW

**Comment by sbesson** [comment]
@lunarthegrey the changes caused Travis CI to fail. This might be related to the `postgres_exporter` release bump in 9bd9d34? Could you try either reverting the the version increment or fixing the tests ?

**Comment by lunarthegrey** [comment]
@sbesson, strange as I deployed this in production with the changes on Debian 10. I will make a commit reverting the version change and see what happens. I couldn't get the exporter to work with the previous version at all, had some obscure error that I didn't save.

**Comment by sbesson** [comment]
@lunarthegrey looking at the upstream library, I suspect the test failures were due to https://github.com/wrouesnel/postgres_exporter/pull/215 which breaks the exporter metrics format in order to support multi-server by introducing the `server` label.

I see reverting to the current version sufficed to fix the tests. Thoughts about getting this in as a patch release allowing consumers like you to override the version of the library via playbook vars  for now? /cc @joshmoore @manics

**Comment by joshmoore** [comment]
No objections to getting the move from main to defaults in and tagged as 0.2.2.

**Comment by lunarthegrey** [comment]
@sbesson, nice find. Seems good to me! Then people can override it in their playbooks anyways like I do.

**Comment by sbesson** [comment]
Many thanks for your contribution @lunarthegrey. I pushed two additional commits to document the new variables in the readme and update the top-level license.

The new version of the role has been tagged and is now available from Galaxy - https://galaxy.ansible.com/ome/prometheus_postgres.

**Comment by lunarthegrey** [comment]
Of course @sbesson, thanks for maintaining this role. It seems like the only maintained Ansible role for postgres_exporter currently. Also the best one, the YAML is solid and methods aren't hacky.

**Pull request merged**
