### PR TITLE
defaults/main.yml: Add latest version

### PR DESCRIPTION
**Pull request by bryanasdev000**
Update to the latest version available.

Signed-off-by: Bryan A. S <bryanasdev000@gmail.com>

### CODE REVIEW

**Comment by manics** [comment]
Thanks for updating this role.

Judging by the failing CI test it looks like the output metrics may have changed. Since we'll need to update the downstream uses of this role it'll take longer than normal before we can figure out the changes and merge this. It's something we've been planning to do though, so we very much appreciate your help in getting this started.

**Comment by bryanasdev000** [comment]
> Thanks for updating this role.
> 
> Judging by the failing CI test it looks like the output metrics may have changed. Since we'll need to update the downstream uses of this role it'll take longer than normal before we can figure out the changes and merge this. It's something we've been planning to do though, so we very much appreciate your help in getting this started.

No problem, in my humble opinion this is the best role available for this task.

I'm probably going to mess with it a little bit and as I progress I open issues and PRs.

I think of making it similar to the role of the [CloudAlchemy node exporter](https://github.com/cloudalchemy/ansible-node-exporter), automated to the right extent.

Thank you for the hard work!

**Comment by bryanasdev000** [comment]
> Thanks for updating this role.
> 
> Judging by the failing CI test it looks like the output metrics may have changed. Since we'll need to update the downstream uses of this role it'll take longer than normal before we can figure out the changes and merge this. It's something we've been planning to do though, so we very much appreciate your help in getting this started.

No problem, in my humble opinion this is the best role available for this task.

I'm probably going to mess a little bit with it and as I progress I will open issues and PRs.

I think of making it similar to the role of the [CloudAlchemy node exporter](https://github.com/cloudalchemy/ansible-node-exporter), automated to the right extent.

Thank you and the team for the hardwork!

Besides, this pipeline seems to me an excellent opportunity to sit and learn to use the molecule and maybe the tox too.

**Comment by sbesson** [comment]
The bump to the latest `prometheus_postgres` version has now been done in #11 with the Molecule changes associated with the formatting change and released as `ome.prometheus_postgres 0.4.0`

**Pull request closed without merging**
